version: '3.8'
services:
  web:
    build: .
    restart: always
    ports:
      - "5000:5000"
    environment:
      - DEBUG=False
      - SQLALCHEMY_DATABASE_URI=postgresql://mementos_user:gizlisifre@db:5432/mementos_db
    volumes:
      - memory_pics:/app/app/static/memory_pics
      - profile_pics:/app/app/static/profile_pics
    depends_on:
      - db
  db:
    image: postgres:15
    restart: always
    environment:
      - POSTGRES_USER=mementos_user
      - POSTGRES_PASSWORD=gizlisifre
      - POSTGRES_DB=mementos_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data:
  memory_pics:
  profile_pics: