"""add verification and 2fa

Revision ID: 239aed8620d2
Revises: 0bc95fba4721
Create Date: 2026-05-25 09:43:26.518060

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '239aed8620d2'
down_revision = '0bc95fba4721'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_verified', sa.Boolean(), server_default='0', nullable=False))
        batch_op.add_column(sa.Column('verification_code', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('require_2fa', sa.Boolean(), server_default='0', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('require_2fa')
        batch_op.drop_column('verification_code')
        batch_op.drop_column('is_verified')

    # ### end Alembic commands ###
