"""add comment likes

Revision ID: 82a222d3c8bf
Revises: c0d936ed50be
Create Date: 2026-06-11 17:15:58.021081

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '82a222d3c8bf'
down_revision = 'c0d936ed50be'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comment_like',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('comment_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['comment_id'], ['comment.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('comment_like', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_comment_like_comment_id'), ['comment_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_comment_like_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comment_like', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_comment_like_user_id'))
        batch_op.drop_index(batch_op.f('ix_comment_like_comment_id'))

    op.drop_table('comment_like')
    # ### end Alembic commands ###
